mono: add BBCLASSEXTEND=native to mono-6.xx.inc
DynamicDevices/meta-mono pull request #149
Opened 2022-09-26 14:31 UTC by mferland

This patch fixes building mono-6 along with the meta-freescale layer. The missing BBCLASSEXTEND definition was causing the mono-native package to depend on zlib and libatomic-ops instead of zlib-native and libatomic-ops-native.

The error I observed was:

ERROR: mono-native-6.12.0.161-r0 do_prepare_recipe_sysroot: Manifest /workdir/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-zlib.populate_sysroot not found in imx8mn_ddr4_evk cortexa53 armv8a-crc armv8a aarch64 allarch x86_64_x86_64-nativesdk (variant '')? ERROR: Logfile of failure stored in: /workdir/build/tmp/work/x86_64-linux/mono-native/6.12.0.161-r0/temp/log.do_prepare_recipe_sysroot.1588124 ERROR: Task (/workdir/yocto/meta-mono/recipes-mono/mono/mono-native_6.12.0.161.bb:do_prepare_recipe_sysroot) failed with exit code '1'

Note that this error does not happen when building for qemuarm (not sure why).

See #148.

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>

2022-10-13 12:13 UTC, ajlennon commented
Apologies for the lack of response. I've been away on holiday and currently playing catch-up. Will get this built on the CI.

2022-10-17 07:56 UTC, ajlennon commented
ok I seem to be getting CI build errors

https://github.com/DynamicDevices/meta-mono/actions/runs/3263265493/jobs/5361833856

2022-10-19 19:10 UTC, mferland commented
Thanks, will look into it.

2022-10-25 15:28 UTC, mferland commented
I have something that builds here. Would be nice to see if this works on your auto-builder. I had a hard time figuring out what was wrong but I think that I finally understand the reason behind the failure. This is not the ideal fix TBH. I think we should rethink how the mono recipes are structured to facilitate native builds for example.

2022-10-26 10:03 UTC, ajlennon commented
Hi @mferland have kicked off a run. I think it'll automatically run for any future PRs

2022-11-01 09:26 UTC, ajlennon commented
I think I have figured out the problems with the CI build. I needed to update the build container. 

Now I am seeing odd dependency issues

https://github.com/DynamicDevices/meta-mono/actions/runs/3322195012/jobs/5586626613

2022-11-08 19:26 UTC, ajlennon commented
Hi - so I have been sorting out CI build. I've updated the build container and kirkstone is building and testing successfully.

Your PR is failing to build. Can you have a look and see what might be the problem please @mferland ?

Thanks!

2022-11-09 13:40 UTC, mferland commented
Hi Alex, thanks for updating the container. Will look into it.

2022-12-12 12:15 UTC, electroScorpion requested changes
Please check your changes in recipes-mono/mono/mono-6.xx.inc in comparison of the Yoco [native class](https://docs.yoctoproject.org/4.0.5/ref-manual/classes.html#native-bbclass) documentation.

2022-12-12 12:15 UTC, electroScorpion commented on recipes-mono/mono/mono-6.xx.inc
> +DEPENDS:class-target += "zlib libatomic-ops cmake-native"
# Maybe Wrong usage of class-target and class-native?
I understand the Yocto-Documentation of [native class](https://docs.yoctoproject.org/4.0.5/ref-manual/classes.html#native-bbclass) so that the *class-target* and *class-native* statements are only used in \<recipe\>-native.bb recipes. Therefore i think it is the wrong usage here and leads to the error in  the [Buildpipeline](https://github.com/DynamicDevices/meta-mono/actions/runs/3322195012/jobs/5586626613). I have done a clean build on my local machine and the following error disappears and mono builds and runs successfully: 


```
ERROR: test-image-mono-1.0-r0 do_rootfs: Could not invoke dnf. Command '/__w/meta-mono/meta-mono/kirkstone/build/tmp/work/qemuarm64-poky-linux/test-image-mono/1.0-r0/recipe-sysroot-native/usr/bin/dnf -v --rpmverbosity=info -y -c /__w/meta-mono/meta-mono/kirkstone/build/tmp/work/qemuarm64-poky-linux/test-image-mono/1.0-r0/rootfs/etc/dnf/dnf.conf --setopt=reposdir=/__w/meta-mono/meta-mono/kirkstone/build/tmp/work/qemuarm64-poky-linux/test-image-mono/1.0-r0/rootfs/etc/yum.repos.d --installroot=/__w/meta-mono/meta-mono/kirkstone/build/tmp/work/qemuarm64-poky-linux/test-image-mono/1.0-r0/rootfs --setopt=logdir=/__w/meta-mono/meta-mono/kirkstone/build/tmp/work/qemuarm64-poky-linux/test-image-mono/1.0-r0/temp --repofrompath=oe-repo,/__w/meta-mono/meta-mono/kirkstone/build/tmp/work/qemuarm64-poky-linux/test-image-mono/1.0-r0/oe-rootfs-repo --nogpgcheck install dnf dotnet dotnet-helloworld mono mono-helloworld msbuild packagegroup-base-extended packagegroup-core-boot packagegroup-core-ssh-dropbear packagegroup-core-x11-base packagegroup-core-x11-sato psplash rpm run-postinsts tzdata locale-base-en-us locale-base-en-gb' returned 1:
DNF version: 4.11.1
cachedir: /__w/meta-mono/meta-mono/kirkstone/build/tmp/work/qemuarm64-poky-linux/test-image-mono/1.0-r0/rootfs/var/cache/dnf
Added oe-repo repo from /__w/meta-mono/meta-mono/kirkstone/build/tmp/work/qemuarm64-poky-linux/test-image-mono/1.0-r0/oe-rootfs-repo
User-Agent: falling back to 'libdnf': could not detect OS or basearch
repo: using cache for: oe-repo
oe-repo: using metadata from Tue 01 Nov 2022 09:23:09 AM UTC.
Last metadata expiration check: 0:00:01 ago on Tue 01 Nov 2022 09:25:27 AM UTC.
--> Starting dependency resolution
--> Finished dependency resolution
Error: 
 Problem 1: conflicting requests
  - nothing provides mono-gac needed by mono-6.12.0.1[61](https://github.com/DynamicDevices/meta-mono/actions/runs/3322195012/jobs/5586626613#step:7:62)-r0.cortexa57
  - nothing provides mono-libs-4.5 needed by mono-6.12.0.161-r0.cortexa57
 Problem 2: package msbuild-16.6-r0.cortexa57 requires mono, but none of the providers can be installed
  - conflicting requests
  - nothing provides mono-gac needed by mono-6.12.0.161-r0.cortexa57
  - nothing provides mono-libs-4.5 needed by mono-6.12.0.161-r0.cortexa57
 Problem 3: package mono-helloworld-1.2-r0.cortexa57 requires mono, but none of the providers can be installed
  - conflicting requests
  - nothing provides mono-gac needed by mono-6.12.0.161-r0.cortexa57
  - nothing provides mono-libs-4.5 needed by mono-6.12.0.161-r0.cortexa57
(try to add '--skip-broken' to skip uninstallable packages) 
```

# Fix
To fix it i used the old statement
```
DEPENDS = "zlib libatomic-ops"
```

2022-12-16 07:05 UTC, electroScorpion approved these changes

2022-12-20 11:47 UTC, merged

2022-12-20 11:47 UTC, ajlennon commented
That builds and tests thanks. Merging in